name: Build Docker Image and Export Tar

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Docker images to build (comma-separated)'
        required: true
        default: 'aapanel/aapanel:latest,casaos/casaos:latest'
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 👈 添加这一行强制使用 Node.js 24

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm/v7]
    steps:
      - name: Checkout
        uses: actions/checkout@v4   # 这个警告可以暂时忽略

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and save Docker image
        run: |
          mkdir -p output
          for image in $(echo '${{ github.event.inputs.images }}' | tr ',' ' '); do
            echo "Pulling $image for ${{ matrix.platform }}"
            docker pull --platform ${{ matrix.platform }} $image
            echo "Saving $image"
            docker save $image -o output/$(echo $image | tr '/' '_' | tr ':' '_').tar
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-${{ matrix.platform }}
          path: output/*.tar
